[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[lib]

name = "hello_world" 

[dev-dependencies]
compiletest_rs = "*" #compiletests are used to test compile-time invariants asserted by strongly typed NodeTrees